version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: bh-zookeeper-fp
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: bh-kafka-fp
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    depends_on:
      - zookeeper

  postgres:
    image: postgres
    container_name: postgresdb-fp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container-fp
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongo:
    image: mongo
    container_name: mongodb-container-fp
    ports:
      - "28017:27017"

  rabbitmq:
    image: 64c5d44756353cab381ecea7144af8870942bacbd72e6c205fec51ab3a7f8f32
    container_name: rabbitmq-container-fp
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch-container-fp
    environment:
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=pgubMOXQGlrxfLQovc7K
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
