spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: ticket-search-service
          uri: lb://TICKET-SEARCH-SERVICE
          predicates:
            - Path=/api/v1/searches/**

        - id: basket-service
          uri: lb://BASKET-SERVICE
          predicates:
            - Path= /api/v1/baskets/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: journey-service
          uri: lb://JOURNEY-SERVICE
          predicates:
            - Path=/api/v1/journeys/**
  main:
    web-application-type:
      reactive
    allow-bean-definition-overriding:
        true


server:
  port: 9000



